<#
.SYNOPSIS
    Generate the .env configuration file for Smart Weight System.

.DESCRIPTION
    Called by the Inno Setup installer after file extraction.
    Reads values collected by the wizard and writes them to InstallDir\.env.

.PARAMETER PrinterInterface
    USB      = raw USB Printer Class (\\.\USBPRINxx)  PRINT_MODE=RAW_DIRECT
    COM      = USB-CDC serial mode                     PRINT_MODE=RAW_DIRECT
    WINDOWS  = Windows print spooler (Get-Printer)     PRINT_MODE=WINDOWS
#>
param(
    [Parameter(Mandatory)][string]$InstallDir,
    [string]$PrinterUsbDevice  = '',
    [string]$PrinterInterface  = 'USB',
    [string]$PrinterComPort    = '',
    [string]$ScalePort         = '',
    [string]$DjangoUrl         = '',
    [string]$DjangoToken       = '',
    [string]$PlantId           = 'A1',
    [string]$StationId         = 'ST01'
)

$ErrorActionPreference = 'Stop'
$envPath = Join-Path $InstallDir '.env'

$effectivePrinterInterface = $PrinterInterface.ToUpper()

# ── Resolve print mode and device values ──────────────────────────────────────
$printMode          = 'WINDOWS'
$printerAutoDetect  = 'false'
$printerUsbDevOut   = ''
$printerComPortOut  = ''
$printerDeviceOut   = ''    # PRINTER_DEVICE  — Windows share name for copy /b
$printerNameOut     = ''    # PRINTER_NAME    — full name for Get-Printer health check

switch ($effectivePrinterInterface) {

    'WINDOWS' {
        # Printer selected from Windows print spooler list.
        # PrinterUsbDevice contains "FullName::ShareName" (encoded by detect-hardware.ps1).
        # ShareName is used for copy /b  →  \\localhost\<share>
        # FullName  is used for health   →  Get-Printer -Name <full>
        $printMode = 'WINDOWS'
        if ($PrinterUsbDevice -match '::') {
            $parts             = $PrinterUsbDevice -split '::', 2
            $printerNameOut    = $parts[0].Trim()    # full name
            $printerDeviceOut  = $parts[1].Trim()    # share name
        } else {
            $printerNameOut    = $PrinterUsbDevice.Trim()
            $printerDeviceOut  = $PrinterUsbDevice.Trim()
        }
        # If no share name was found (printer not shared yet), default to the
        # print-service's built-in default so the service at least starts.
        if (-not $printerDeviceOut) { $printerDeviceOut = 'TVSLP46NEO' }
        if (-not $printerNameOut)   { $printerNameOut   = $printerDeviceOut }
    }

    'COM' {
        # USB-CDC mode printer — COM port for raw serial write
        $printMode         = 'RAW_DIRECT'
        $printerComPortOut = $PrinterUsbDevice    # reuse field
    }

    default {
        # USB Printer Class — \\.\USBPRINxx raw write (driverless)
        $printMode         = 'RAW_DIRECT'
        $printerUsbDevOut  = $PrinterUsbDevice
    }
}

$scaleAutoDetect = if ($ScalePort) { 'false' } else { 'true' }

# ── Write .env ────────────────────────────────────────────────────────────────
$content = @"
# ============================================================
# Smart Weight System — Station Configuration
# Generated by installer on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# ============================================================

# -- Station Identity -----------------------------------------
STATION_ID=$StationId
PLANT_ID=$PlantId

# -- Weight Service (port 5000) -------------------------------
SERIAL_PORT=$ScalePort
SCALE_AUTO_DETECT=$scaleAutoDetect
SCALE_NO_DATA_TIMEOUT_MS=15000
SERIAL_BAUD_RATE=9600
SERIAL_DATA_BITS=8
SERIAL_PARITY=none
SERIAL_STOP_BITS=1
SIMULATE_SERIAL=false
WEIGHT_API_PORT=5000
STABILITY_THRESHOLD_MS=1500
STABILITY_TOLERANCE_KG=0.02
LOG_LEVEL=info

# -- Print Service (port 5001) --------------------------------
# PRINT_MODE=WINDOWS   : use Windows print spooler (copy /b to \\localhost\PRINTER_DEVICE)
# PRINT_MODE=RAW_DIRECT: bypass spooler, write directly to USB or COM port
PRINTER_DRIVER=tspl
PRINT_MODE=$printMode
PRINTER_INTERFACE=$effectivePrinterInterface
PRINTER_AUTO_DETECT=$printerAutoDetect
PRINTER_USB_DEVICE=$printerUsbDevOut
PRINTER_COM_PORT=$printerComPortOut
PRINTER_DEVICE=$printerDeviceOut
PRINTER_NAME=$printerNameOut
PRINTER_LABEL_WIDTH=50
PRINTER_LABEL_HEIGHT=50
PRINTER_DPI=203
PRINT_API_PORT=5001

# -- Sync Service (port 5002) ---------------------------------
SYNC_API_PORT=5002
DJANGO_SERVER_URL=$DjangoUrl
DJANGO_API_TOKEN=$DjangoToken
SYNC_RETRY_INTERVAL_MS=60000
MASTER_SYNC_INTERVAL_MS=300000
SYNC_PUSH_TIMEOUT_MS=10000
BAG_SYNC_INTERVAL_MS=10000
OFFLINE_DAY_SEQ_START=90
OFFLINE_DAY_SEQ_END=99

# -- Web UI (port 3000) ---------------------------------------
WEB_UI_PORT=3000

# -- Launcher -------------------------------------------------
WEIGHT_SERVICE_URL=http://localhost:5000
LAUNCHER_HEALTH_PORT=5099
"@

$content | Set-Content $envPath -Encoding UTF8
Write-Host "[OK] .env written to: $envPath"

# ── Print summary so installer log shows what was set ─────────────────────────
Write-Host "  STATION_ID        = $StationId"
Write-Host "  PLANT_ID          = $PlantId"
Write-Host "  SERIAL_PORT       = $(if ($ScalePort) { $ScalePort } else { '(auto-detect)' })"
Write-Host "  PRINT_MODE        = $printMode"
Write-Host "  PRINTER_INTERFACE = $effectivePrinterInterface"
Write-Host "  PRINTER_DEVICE    = $printerDeviceOut"
Write-Host "  PRINTER_NAME      = $printerNameOut"
Write-Host "  DJANGO_SERVER_URL = $DjangoUrl"
