<#
.SYNOPSIS
    Generate the .env configuration file for Smart Weight System.

.DESCRIPTION
    Called by the Inno Setup installer after file extraction.
    Reads values collected by the wizard and writes them to InstallDir\.env,
    ready to be consumed by all four services on first start.

.PARAMETER InstallDir
    Root installation directory (e.g. C:\SmartWeightSystem).

.PARAMETER PrinterUsbDevice
    USB device path detected for the label printer (e.g. \\.\USBPRIN01).
    Leave empty to use PRINTER_AUTO_DETECT=true.

.PARAMETER ScalePort
    COM port for the weighing scale (e.g. COM3).
    Leave empty to use SCALE_AUTO_DETECT=true.

.PARAMETER DjangoUrl
    Django ERP server URL (e.g. http://192.168.1.100:8000).

.PARAMETER DjangoToken
    API bearer token from the Django WeighStation admin table.

.PARAMETER PlantId
    Plant / facility identifier (e.g. A1).

.PARAMETER StationId
    Station identifier — must be unique per plant (e.g. ST01).
#>
param(
    [Parameter(Mandatory)][string]$InstallDir,
    [string]$PrinterUsbDevice  = '',
    [string]$PrinterInterface  = 'USB',   # 'USB' = USBPRIN path, 'COM' = USB-CDC serial
    [string]$PrinterComPort    = '',      # only used when PrinterInterface=COM
    [string]$ScalePort         = '',
    [string]$DjangoUrl         = '',
    [string]$DjangoToken       = '',
    [string]$PlantId           = 'A1',
    [string]$StationId         = 'ST01'
)

$ErrorActionPreference = 'Stop'

$envPath = Join-Path $InstallDir '.env'

# Determine print mode and interface from wizard selection
$printMode        = 'RAW_DIRECT'   # installer always uses driverless mode
$printerAutoDetect = 'false'        # explicit device selected in wizard
$scaleAutoDetect  = if ($ScalePort) { 'false' } else { 'true' }

# For COM-mode printer (USB-CDC), use the COM port for printing
$effectivePrinterInterface = $PrinterInterface.ToUpper()
if ($effectivePrinterInterface -eq 'COM') {
    $PrinterComPort   = $PrinterUsbDevice   # field reused as COM port in COM mode
    $PrinterUsbDevice = ''
}

$content = @"
# ============================================================
# Smart Weight System — Station Configuration
# Generated by installer on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# ============================================================

# -- Station Identity -----------------------------------------
STATION_ID=$StationId
PLANT_ID=$PlantId

# -- Weight Service (port 5000) -------------------------------
# USB-serial adapter COM port. Auto-detected if blank.
SERIAL_PORT=$ScalePort
SCALE_AUTO_DETECT=$scaleAutoDetect
SERIAL_BAUD_RATE=9600
SERIAL_DATA_BITS=8
SERIAL_PARITY=none
SERIAL_STOP_BITS=1
SIMULATE_SERIAL=false
WEIGHT_API_PORT=5000
STABILITY_THRESHOLD_MS=1500
STABILITY_TOLERANCE_KG=0.02
LOG_LEVEL=info

# -- Print Service (port 5001) --------------------------------
PRINTER_DRIVER=tspl
PRINT_MODE=$printMode
PRINTER_INTERFACE=$effectivePrinterInterface
PRINTER_AUTO_DETECT=$printerAutoDetect
PRINTER_USB_DEVICE=$PrinterUsbDevice
PRINTER_COM_PORT=$PrinterComPort
PRINTER_DEVICE=
PRINTER_NAME=
PRINTER_LABEL_WIDTH=50
PRINTER_LABEL_HEIGHT=50
PRINTER_DPI=203
PRINT_API_PORT=5001

# -- Sync Service (port 5002) ---------------------------------
SYNC_API_PORT=5002
DJANGO_SERVER_URL=$DjangoUrl
DJANGO_API_TOKEN=$DjangoToken
SYNC_RETRY_INTERVAL_MS=60000
MASTER_SYNC_INTERVAL_MS=3600000
SYNC_PUSH_TIMEOUT_MS=10000
BAG_SYNC_INTERVAL_MS=10000
OFFLINE_DAY_SEQ_START=90
OFFLINE_DAY_SEQ_END=99

# -- Web UI (port 3000) ---------------------------------------
WEB_UI_PORT=3000

# -- Hardware Manager -----------------------------------------
WEIGHT_SERVICE_URL=http://localhost:5000
LAUNCHER_HEALTH_PORT=5099
"@

$content | Set-Content $envPath -Encoding UTF8
Write-Host "[OK] .env written to: $envPath"
